namespace FortniteTweaks
{
    partial class OtherTweaks
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(OtherTweaks));
            panel1 = new Panel();
            minimizeButton = new SiticoneNetCoreUI.SiticoneButton();
            closeButton = new SiticoneNetCoreUI.SiticoneButton();
            label3 = new Label();
            label4 = new Label();
            label1 = new Label();
            label2 = new Label();
            disableWinTelemetry = new SiticoneNetCoreUI.SiticoneButton();
            windowsIOTweaks = new SiticoneNetCoreUI.SiticoneButton();
            windowsPowerPlan = new SiticoneNetCoreUI.SiticoneButton();
            windowsGeneralSettings = new SiticoneNetCoreUI.SiticoneButton();
            debloatWindows = new SiticoneNetCoreUI.SiticoneButton();
            rebloat_Windows = new SiticoneNetCoreUI.SiticoneButton();
            debloatStartup = new SiticoneNetCoreUI.SiticoneButton();
            i = new SiticoneNetCoreUI.SiticoneButton();
            i2 = new SiticoneNetCoreUI.SiticoneButton();
            cpuTweaks = new SiticoneNetCoreUI.SiticoneButton();
            cleanTempFiles = new SiticoneNetCoreUI.SiticoneButton();
            menuKillTime = new SiticoneNetCoreUI.SiticoneButton();
            msiUtlity = new SiticoneNetCoreUI.SiticoneButton();
            back = new SiticoneNetCoreUI.SiticoneButton();
            warrning = new Label();
            createRestorePoint = new SiticoneNetCoreUI.SiticoneButton();
            progressBarRestore = new ProgressBar();
            lblRestoreStatus = new Label();
            siticoneButton1 = new SiticoneNetCoreUI.SiticoneButton();
            panel1.SuspendLayout();
            SuspendLayout();
            // 
            // panel1
            // 
            panel1.BackColor = Color.FromArgb(25, 25, 25);
            panel1.Controls.Add(minimizeButton);
            panel1.Controls.Add(closeButton);
            panel1.Controls.Add(label3);
            panel1.Location = new Point(0, 1);
            panel1.Name = "panel1";
            panel1.Size = new Size(993, 34);
            panel1.TabIndex = 21;
            panel1.Paint += panel1_Paint;
            panel1.MouseDown += pnl1TitleBar_MouseDown;
            // 
            // minimizeButton
            // 
            minimizeButton.AccessibleDescription = "This button minimizes the program";
            minimizeButton.AccessibleName = "-";
            minimizeButton.AutoSizeBasedOnText = false;
            minimizeButton.BackColor = Color.Transparent;
            minimizeButton.BadgeBackColor = Color.Black;
            minimizeButton.BadgeFont = new Font("Segoe UI", 8F, FontStyle.Bold);
            minimizeButton.BadgeValue = 0;
            minimizeButton.BadgeValueForeColor = Color.White;
            minimizeButton.BorderColor = Color.FromArgb(60, 60, 60);
            minimizeButton.BorderWidth = 2;
            minimizeButton.ButtonBackColor = Color.FromArgb(30, 30, 30);
            minimizeButton.ButtonImage = null;
            minimizeButton.ButtonTextLeftPadding = 0;
            minimizeButton.CanBeep = true;
            minimizeButton.CanGlow = true;
            minimizeButton.CanShake = true;
            minimizeButton.ContextMenuStripEx = null;
            minimizeButton.CornerRadiusBottomLeft = 6;
            minimizeButton.CornerRadiusBottomRight = 6;
            minimizeButton.CornerRadiusTopLeft = 6;
            minimizeButton.CornerRadiusTopRight = 6;
            minimizeButton.CustomCursor = Cursors.Default;
            minimizeButton.DisabledTextColor = Color.FromArgb(150, 150, 150);
            minimizeButton.EnableLongPress = false;
            minimizeButton.EnablePressAnimation = true;
            minimizeButton.EnableRippleEffect = true;
            minimizeButton.EnableShadow = false;
            minimizeButton.EnableTextWrapping = false;
            minimizeButton.Font = new Font("Segoe UI Semibold", 10.2F);
            minimizeButton.GlowColor = Color.FromArgb(30, 255, 255, 255);
            minimizeButton.GlowIntensity = 100;
            minimizeButton.GlowRadius = 20F;
            minimizeButton.GradientBackground = false;
            minimizeButton.GradientColor = Color.FromArgb(0, 227, 64);
            minimizeButton.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            minimizeButton.HintText = null;
            minimizeButton.HoverBackColor = Color.FromArgb(50, 50, 50);
            minimizeButton.HoverFontStyle = FontStyle.Regular;
            minimizeButton.HoverTextColor = Color.White;
            minimizeButton.HoverTransitionDuration = 250;
            minimizeButton.ImageAlign = ContentAlignment.MiddleLeft;
            minimizeButton.ImagePadding = 5;
            minimizeButton.ImageSize = new Size(16, 16);
            minimizeButton.IsRadial = false;
            minimizeButton.IsReadOnly = false;
            minimizeButton.IsToggleButton = false;
            minimizeButton.IsToggled = false;
            minimizeButton.Location = new Point(920, 3);
            minimizeButton.LongPressDurationMS = 1000;
            minimizeButton.Name = "minimizeButton";
            minimizeButton.NormalFontStyle = FontStyle.Regular;
            minimizeButton.ParticleColor = Color.FromArgb(200, 200, 200);
            minimizeButton.ParticleCount = 15;
            minimizeButton.PressAnimationScale = 0.97F;
            minimizeButton.PressedBackColor = Color.FromArgb(40, 40, 40);
            minimizeButton.PressedFontStyle = FontStyle.Regular;
            minimizeButton.PressTransitionDuration = 150;
            minimizeButton.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            minimizeButton.RippleColor = Color.FromArgb(100, 100, 100);
            minimizeButton.RippleOpacity = 0.3F;
            minimizeButton.RippleRadiusMultiplier = 0.6F;
            minimizeButton.ShadowBlur = 5;
            minimizeButton.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            minimizeButton.ShadowOffset = new Point(2, 2);
            minimizeButton.ShakeDuration = 500;
            minimizeButton.ShakeIntensity = 5;
            minimizeButton.Size = new Size(32, 28);
            minimizeButton.TabIndex = 2;
            minimizeButton.Text = "-";
            minimizeButton.TextAlign = ContentAlignment.MiddleCenter;
            minimizeButton.TextColor = Color.White;
            minimizeButton.TooltipText = null;
            minimizeButton.UseAdvancedRendering = true;
            minimizeButton.UseParticles = false;
            minimizeButton.Click += minimizeButton_Click;
            minimizeButton.MouseClick += apply;
            minimizeButton.MouseEnter += hover;
            // 
            // closeButton
            // 
            closeButton.AccessibleDescription = "This closes the Key System";
            closeButton.AccessibleName = "X";
            closeButton.AutoSizeBasedOnText = false;
            closeButton.BackColor = Color.Transparent;
            closeButton.BadgeBackColor = Color.Black;
            closeButton.BadgeFont = new Font("Segoe UI", 8F, FontStyle.Bold);
            closeButton.BadgeValue = 0;
            closeButton.BadgeValueForeColor = Color.White;
            closeButton.BorderColor = Color.FromArgb(60, 60, 60);
            closeButton.BorderWidth = 2;
            closeButton.ButtonBackColor = Color.FromArgb(30, 30, 30);
            closeButton.ButtonImage = null;
            closeButton.ButtonTextLeftPadding = 0;
            closeButton.CanBeep = true;
            closeButton.CanGlow = true;
            closeButton.CanShake = true;
            closeButton.ContextMenuStripEx = null;
            closeButton.CornerRadiusBottomLeft = 6;
            closeButton.CornerRadiusBottomRight = 6;
            closeButton.CornerRadiusTopLeft = 6;
            closeButton.CornerRadiusTopRight = 6;
            closeButton.CustomCursor = Cursors.Default;
            closeButton.DisabledTextColor = Color.FromArgb(150, 150, 150);
            closeButton.EnableLongPress = false;
            closeButton.EnablePressAnimation = true;
            closeButton.EnableRippleEffect = true;
            closeButton.EnableShadow = false;
            closeButton.EnableTextWrapping = false;
            closeButton.Font = new Font("Segoe UI Semibold", 10.2F);
            closeButton.GlowColor = Color.Red;
            closeButton.GlowIntensity = 100;
            closeButton.GlowRadius = 20F;
            closeButton.GradientBackground = false;
            closeButton.GradientColor = Color.FromArgb(0, 227, 64);
            closeButton.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            closeButton.HintText = null;
            closeButton.HoverBackColor = Color.FromArgb(50, 50, 50);
            closeButton.HoverFontStyle = FontStyle.Regular;
            closeButton.HoverTextColor = Color.White;
            closeButton.HoverTransitionDuration = 250;
            closeButton.ImageAlign = ContentAlignment.MiddleLeft;
            closeButton.ImagePadding = 5;
            closeButton.ImageSize = new Size(16, 16);
            closeButton.IsRadial = false;
            closeButton.IsReadOnly = false;
            closeButton.IsToggleButton = false;
            closeButton.IsToggled = false;
            closeButton.Location = new Point(958, 3);
            closeButton.LongPressDurationMS = 1000;
            closeButton.Name = "closeButton";
            closeButton.NormalFontStyle = FontStyle.Regular;
            closeButton.ParticleColor = Color.FromArgb(200, 200, 200);
            closeButton.ParticleCount = 15;
            closeButton.PressAnimationScale = 0.97F;
            closeButton.PressedBackColor = Color.FromArgb(40, 40, 40);
            closeButton.PressedFontStyle = FontStyle.Regular;
            closeButton.PressTransitionDuration = 150;
            closeButton.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            closeButton.RippleColor = Color.FromArgb(100, 100, 100);
            closeButton.RippleOpacity = 0.3F;
            closeButton.RippleRadiusMultiplier = 0.6F;
            closeButton.ShadowBlur = 5;
            closeButton.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            closeButton.ShadowOffset = new Point(2, 2);
            closeButton.ShakeDuration = 500;
            closeButton.ShakeIntensity = 5;
            closeButton.Size = new Size(32, 28);
            closeButton.TabIndex = 1;
            closeButton.Text = "X";
            closeButton.TextAlign = ContentAlignment.MiddleCenter;
            closeButton.TextColor = Color.White;
            closeButton.TooltipText = null;
            closeButton.UseAdvancedRendering = true;
            closeButton.UseParticles = false;
            closeButton.Click += btnClose_Click;
            closeButton.MouseClick += apply;
            closeButton.MouseEnter += hover;
            // 
            // label3
            // 
            label3.AutoSize = true;
            label3.Font = new Font("Microsoft YaHei UI", 9.75F, FontStyle.Bold, GraphicsUnit.Point, 0);
            label3.ForeColor = Color.White;
            label3.Location = new Point(3, 12);
            label3.Name = "label3";
            label3.Size = new Size(182, 19);
            label3.TabIndex = 0;
            label3.Text = "Lunchbox Fortnite Tweaks";
            label3.MouseDown += pnl1TitleBar_MouseDown;
            // 
            // label4
            // 
            label4.AutoSize = true;
            label4.Font = new Font("Microsoft YaHei UI Light", 8.25F, FontStyle.Regular, GraphicsUnit.Point, 0);
            label4.ForeColor = Color.White;
            label4.Location = new Point(427, 125);
            label4.Name = "label4";
            label4.Size = new Size(131, 16);
            label4.TabIndex = 27;
            label4.Text = "you are at: Other Tweaks";
            // 
            // label1
            // 
            label1.Font = new Font("Microsoft YaHei UI", 20.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            label1.ForeColor = Color.White;
            label1.Location = new Point(244, 86);
            label1.Name = "label1";
            label1.Size = new Size(505, 39);
            label1.TabIndex = 25;
            label1.Text = "Lunchbox Fortnite Tweaks";
            label1.TextAlign = ContentAlignment.MiddleCenter;
            // 
            // label2
            // 
            label2.Font = new Font("Microsoft YaHei UI", 14.25F, FontStyle.Regular, GraphicsUnit.Point, 0);
            label2.ForeColor = Color.White;
            label2.Location = new Point(244, 58);
            label2.Name = "label2";
            label2.Size = new Size(498, 28);
            label2.TabIndex = 26;
            label2.Text = "Welcome to";
            label2.TextAlign = ContentAlignment.MiddleCenter;
            // 
            // disableWinTelemetry
            // 
            disableWinTelemetry.AccessibleDescription = "";
            disableWinTelemetry.AccessibleName = "Disable Windows Telemetry";
            disableWinTelemetry.AutoSizeBasedOnText = false;
            disableWinTelemetry.BackColor = Color.Transparent;
            disableWinTelemetry.BadgeBackColor = Color.Black;
            disableWinTelemetry.BadgeFont = new Font("Microsoft YaHei UI", 11.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            disableWinTelemetry.BadgeValue = 0;
            disableWinTelemetry.BadgeValueForeColor = Color.White;
            disableWinTelemetry.BorderColor = Color.FromArgb(60, 60, 60);
            disableWinTelemetry.BorderWidth = 2;
            disableWinTelemetry.ButtonBackColor = Color.FromArgb(30, 30, 30);
            disableWinTelemetry.ButtonImage = null;
            disableWinTelemetry.ButtonTextLeftPadding = 0;
            disableWinTelemetry.CanBeep = true;
            disableWinTelemetry.CanGlow = true;
            disableWinTelemetry.CanShake = true;
            disableWinTelemetry.ContextMenuStripEx = null;
            disableWinTelemetry.CornerRadiusBottomLeft = 6;
            disableWinTelemetry.CornerRadiusBottomRight = 6;
            disableWinTelemetry.CornerRadiusTopLeft = 6;
            disableWinTelemetry.CornerRadiusTopRight = 6;
            disableWinTelemetry.CustomCursor = Cursors.Default;
            disableWinTelemetry.DisabledTextColor = Color.FromArgb(150, 150, 150);
            disableWinTelemetry.EnableLongPress = false;
            disableWinTelemetry.EnablePressAnimation = true;
            disableWinTelemetry.EnableRippleEffect = true;
            disableWinTelemetry.EnableShadow = false;
            disableWinTelemetry.EnableTextWrapping = false;
            disableWinTelemetry.Font = new Font("Microsoft YaHei UI", 14.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            disableWinTelemetry.GlowColor = Color.Cyan;
            disableWinTelemetry.GlowIntensity = 100;
            disableWinTelemetry.GlowRadius = 20F;
            disableWinTelemetry.GradientBackground = false;
            disableWinTelemetry.GradientColor = Color.FromArgb(0, 227, 64);
            disableWinTelemetry.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            disableWinTelemetry.HintText = null;
            disableWinTelemetry.HoverBackColor = Color.FromArgb(50, 50, 50);
            disableWinTelemetry.HoverFontStyle = FontStyle.Regular;
            disableWinTelemetry.HoverTextColor = Color.White;
            disableWinTelemetry.HoverTransitionDuration = 250;
            disableWinTelemetry.ImageAlign = ContentAlignment.MiddleLeft;
            disableWinTelemetry.ImagePadding = 5;
            disableWinTelemetry.ImageSize = new Size(16, 16);
            disableWinTelemetry.IsRadial = false;
            disableWinTelemetry.IsReadOnly = false;
            disableWinTelemetry.IsToggleButton = false;
            disableWinTelemetry.IsToggled = false;
            disableWinTelemetry.Location = new Point(12, 171);
            disableWinTelemetry.LongPressDurationMS = 1000;
            disableWinTelemetry.Name = "disableWinTelemetry";
            disableWinTelemetry.NormalFontStyle = FontStyle.Regular;
            disableWinTelemetry.ParticleColor = Color.FromArgb(200, 200, 200);
            disableWinTelemetry.ParticleCount = 15;
            disableWinTelemetry.PressAnimationScale = 0.97F;
            disableWinTelemetry.PressedBackColor = Color.FromArgb(40, 40, 40);
            disableWinTelemetry.PressedFontStyle = FontStyle.Regular;
            disableWinTelemetry.PressTransitionDuration = 150;
            disableWinTelemetry.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            disableWinTelemetry.RippleColor = Color.FromArgb(100, 100, 100);
            disableWinTelemetry.RippleOpacity = 0.3F;
            disableWinTelemetry.RippleRadiusMultiplier = 0.6F;
            disableWinTelemetry.ShadowBlur = 5;
            disableWinTelemetry.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            disableWinTelemetry.ShadowOffset = new Point(2, 2);
            disableWinTelemetry.ShakeDuration = 500;
            disableWinTelemetry.ShakeIntensity = 5;
            disableWinTelemetry.Size = new Size(289, 35);
            disableWinTelemetry.TabIndex = 28;
            disableWinTelemetry.Text = "Disable Windows Telemetry";
            disableWinTelemetry.TextAlign = ContentAlignment.MiddleCenter;
            disableWinTelemetry.TextColor = Color.White;
            disableWinTelemetry.TooltipText = null;
            disableWinTelemetry.UseAdvancedRendering = true;
            disableWinTelemetry.UseParticles = false;
            disableWinTelemetry.Click += win_telemetry_Click;
            disableWinTelemetry.MouseClick += apply;
            disableWinTelemetry.MouseEnter += hover;
            // 
            // windowsIOTweaks
            // 
            windowsIOTweaks.AccessibleDescription = "";
            windowsIOTweaks.AccessibleName = "Windows iO Tweaks";
            windowsIOTweaks.AutoSizeBasedOnText = false;
            windowsIOTweaks.BackColor = Color.Transparent;
            windowsIOTweaks.BadgeBackColor = Color.Black;
            windowsIOTweaks.BadgeFont = new Font("Microsoft YaHei UI", 11.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            windowsIOTweaks.BadgeValue = 0;
            windowsIOTweaks.BadgeValueForeColor = Color.White;
            windowsIOTweaks.BorderColor = Color.FromArgb(60, 60, 60);
            windowsIOTweaks.BorderWidth = 2;
            windowsIOTweaks.ButtonBackColor = Color.FromArgb(30, 30, 30);
            windowsIOTweaks.ButtonImage = null;
            windowsIOTweaks.ButtonTextLeftPadding = 0;
            windowsIOTweaks.CanBeep = true;
            windowsIOTweaks.CanGlow = true;
            windowsIOTweaks.CanShake = true;
            windowsIOTweaks.ContextMenuStripEx = null;
            windowsIOTweaks.CornerRadiusBottomLeft = 6;
            windowsIOTweaks.CornerRadiusBottomRight = 6;
            windowsIOTweaks.CornerRadiusTopLeft = 6;
            windowsIOTweaks.CornerRadiusTopRight = 6;
            windowsIOTweaks.CustomCursor = Cursors.Default;
            windowsIOTweaks.DisabledTextColor = Color.FromArgb(150, 150, 150);
            windowsIOTweaks.EnableLongPress = false;
            windowsIOTweaks.EnablePressAnimation = true;
            windowsIOTweaks.EnableRippleEffect = true;
            windowsIOTweaks.EnableShadow = false;
            windowsIOTweaks.EnableTextWrapping = false;
            windowsIOTweaks.Font = new Font("Microsoft YaHei UI", 14.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            windowsIOTweaks.GlowColor = Color.Cyan;
            windowsIOTweaks.GlowIntensity = 100;
            windowsIOTweaks.GlowRadius = 20F;
            windowsIOTweaks.GradientBackground = false;
            windowsIOTweaks.GradientColor = Color.FromArgb(0, 227, 64);
            windowsIOTweaks.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            windowsIOTweaks.HintText = null;
            windowsIOTweaks.HoverBackColor = Color.FromArgb(50, 50, 50);
            windowsIOTweaks.HoverFontStyle = FontStyle.Regular;
            windowsIOTweaks.HoverTextColor = Color.White;
            windowsIOTweaks.HoverTransitionDuration = 250;
            windowsIOTweaks.ImageAlign = ContentAlignment.MiddleLeft;
            windowsIOTweaks.ImagePadding = 5;
            windowsIOTweaks.ImageSize = new Size(16, 16);
            windowsIOTweaks.IsRadial = false;
            windowsIOTweaks.IsReadOnly = false;
            windowsIOTweaks.IsToggleButton = false;
            windowsIOTweaks.IsToggled = false;
            windowsIOTweaks.Location = new Point(12, 212);
            windowsIOTweaks.LongPressDurationMS = 1000;
            windowsIOTweaks.Name = "windowsIOTweaks";
            windowsIOTweaks.NormalFontStyle = FontStyle.Regular;
            windowsIOTweaks.ParticleColor = Color.FromArgb(200, 200, 200);
            windowsIOTweaks.ParticleCount = 15;
            windowsIOTweaks.PressAnimationScale = 0.97F;
            windowsIOTweaks.PressedBackColor = Color.FromArgb(40, 40, 40);
            windowsIOTweaks.PressedFontStyle = FontStyle.Regular;
            windowsIOTweaks.PressTransitionDuration = 150;
            windowsIOTweaks.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            windowsIOTweaks.RippleColor = Color.FromArgb(100, 100, 100);
            windowsIOTweaks.RippleOpacity = 0.3F;
            windowsIOTweaks.RippleRadiusMultiplier = 0.6F;
            windowsIOTweaks.ShadowBlur = 5;
            windowsIOTweaks.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            windowsIOTweaks.ShadowOffset = new Point(2, 2);
            windowsIOTweaks.ShakeDuration = 500;
            windowsIOTweaks.ShakeIntensity = 5;
            windowsIOTweaks.Size = new Size(211, 35);
            windowsIOTweaks.TabIndex = 29;
            windowsIOTweaks.Text = "Windows iO Tweaks";
            windowsIOTweaks.TextAlign = ContentAlignment.MiddleCenter;
            windowsIOTweaks.TextColor = Color.White;
            windowsIOTweaks.TooltipText = null;
            windowsIOTweaks.UseAdvancedRendering = true;
            windowsIOTweaks.UseParticles = false;
            windowsIOTweaks.Click += windowsIOTweaks_Click;
            windowsIOTweaks.MouseClick += apply;
            windowsIOTweaks.MouseEnter += hover;
            // 
            // windowsPowerPlan
            // 
            windowsPowerPlan.AccessibleDescription = "";
            windowsPowerPlan.AccessibleName = "Windows Power Plan";
            windowsPowerPlan.AutoSizeBasedOnText = false;
            windowsPowerPlan.BackColor = Color.Transparent;
            windowsPowerPlan.BadgeBackColor = Color.Black;
            windowsPowerPlan.BadgeFont = new Font("Microsoft YaHei UI", 11.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            windowsPowerPlan.BadgeValue = 0;
            windowsPowerPlan.BadgeValueForeColor = Color.White;
            windowsPowerPlan.BorderColor = Color.FromArgb(60, 60, 60);
            windowsPowerPlan.BorderWidth = 2;
            windowsPowerPlan.ButtonBackColor = Color.FromArgb(30, 30, 30);
            windowsPowerPlan.ButtonImage = null;
            windowsPowerPlan.ButtonTextLeftPadding = 0;
            windowsPowerPlan.CanBeep = true;
            windowsPowerPlan.CanGlow = true;
            windowsPowerPlan.CanShake = true;
            windowsPowerPlan.ContextMenuStripEx = null;
            windowsPowerPlan.CornerRadiusBottomLeft = 6;
            windowsPowerPlan.CornerRadiusBottomRight = 6;
            windowsPowerPlan.CornerRadiusTopLeft = 6;
            windowsPowerPlan.CornerRadiusTopRight = 6;
            windowsPowerPlan.CustomCursor = Cursors.Default;
            windowsPowerPlan.DisabledTextColor = Color.FromArgb(150, 150, 150);
            windowsPowerPlan.EnableLongPress = false;
            windowsPowerPlan.EnablePressAnimation = true;
            windowsPowerPlan.EnableRippleEffect = true;
            windowsPowerPlan.EnableShadow = false;
            windowsPowerPlan.EnableTextWrapping = false;
            windowsPowerPlan.Font = new Font("Microsoft YaHei UI", 14.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            windowsPowerPlan.GlowColor = Color.Cyan;
            windowsPowerPlan.GlowIntensity = 100;
            windowsPowerPlan.GlowRadius = 20F;
            windowsPowerPlan.GradientBackground = false;
            windowsPowerPlan.GradientColor = Color.FromArgb(0, 227, 64);
            windowsPowerPlan.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            windowsPowerPlan.HintText = null;
            windowsPowerPlan.HoverBackColor = Color.FromArgb(50, 50, 50);
            windowsPowerPlan.HoverFontStyle = FontStyle.Regular;
            windowsPowerPlan.HoverTextColor = Color.White;
            windowsPowerPlan.HoverTransitionDuration = 250;
            windowsPowerPlan.ImageAlign = ContentAlignment.MiddleLeft;
            windowsPowerPlan.ImagePadding = 5;
            windowsPowerPlan.ImageSize = new Size(16, 16);
            windowsPowerPlan.IsRadial = false;
            windowsPowerPlan.IsReadOnly = false;
            windowsPowerPlan.IsToggleButton = false;
            windowsPowerPlan.IsToggled = false;
            windowsPowerPlan.Location = new Point(12, 253);
            windowsPowerPlan.LongPressDurationMS = 1000;
            windowsPowerPlan.Name = "windowsPowerPlan";
            windowsPowerPlan.NormalFontStyle = FontStyle.Regular;
            windowsPowerPlan.ParticleColor = Color.FromArgb(200, 200, 200);
            windowsPowerPlan.ParticleCount = 15;
            windowsPowerPlan.PressAnimationScale = 0.97F;
            windowsPowerPlan.PressedBackColor = Color.FromArgb(40, 40, 40);
            windowsPowerPlan.PressedFontStyle = FontStyle.Regular;
            windowsPowerPlan.PressTransitionDuration = 150;
            windowsPowerPlan.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            windowsPowerPlan.RippleColor = Color.FromArgb(100, 100, 100);
            windowsPowerPlan.RippleOpacity = 0.3F;
            windowsPowerPlan.RippleRadiusMultiplier = 0.6F;
            windowsPowerPlan.ShadowBlur = 5;
            windowsPowerPlan.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            windowsPowerPlan.ShadowOffset = new Point(2, 2);
            windowsPowerPlan.ShakeDuration = 500;
            windowsPowerPlan.ShakeIntensity = 5;
            windowsPowerPlan.Size = new Size(223, 35);
            windowsPowerPlan.TabIndex = 30;
            windowsPowerPlan.Text = "Windows Power Plan";
            windowsPowerPlan.TextAlign = ContentAlignment.MiddleCenter;
            windowsPowerPlan.TextColor = Color.White;
            windowsPowerPlan.TooltipText = null;
            windowsPowerPlan.UseAdvancedRendering = true;
            windowsPowerPlan.UseParticles = false;
            windowsPowerPlan.Click += windowsPowerPlan_Click;
            windowsPowerPlan.MouseClick += apply;
            windowsPowerPlan.MouseEnter += hover;
            // 
            // windowsGeneralSettings
            // 
            windowsGeneralSettings.AccessibleDescription = "";
            windowsGeneralSettings.AccessibleName = "Windows General Settings";
            windowsGeneralSettings.AutoSizeBasedOnText = false;
            windowsGeneralSettings.BackColor = Color.Transparent;
            windowsGeneralSettings.BadgeBackColor = Color.Black;
            windowsGeneralSettings.BadgeFont = new Font("Microsoft YaHei UI", 11.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            windowsGeneralSettings.BadgeValue = 0;
            windowsGeneralSettings.BadgeValueForeColor = Color.White;
            windowsGeneralSettings.BorderColor = Color.FromArgb(60, 60, 60);
            windowsGeneralSettings.BorderWidth = 2;
            windowsGeneralSettings.ButtonBackColor = Color.FromArgb(30, 30, 30);
            windowsGeneralSettings.ButtonImage = null;
            windowsGeneralSettings.ButtonTextLeftPadding = 0;
            windowsGeneralSettings.CanBeep = true;
            windowsGeneralSettings.CanGlow = true;
            windowsGeneralSettings.CanShake = true;
            windowsGeneralSettings.ContextMenuStripEx = null;
            windowsGeneralSettings.CornerRadiusBottomLeft = 6;
            windowsGeneralSettings.CornerRadiusBottomRight = 6;
            windowsGeneralSettings.CornerRadiusTopLeft = 6;
            windowsGeneralSettings.CornerRadiusTopRight = 6;
            windowsGeneralSettings.CustomCursor = Cursors.Default;
            windowsGeneralSettings.DisabledTextColor = Color.FromArgb(150, 150, 150);
            windowsGeneralSettings.EnableLongPress = false;
            windowsGeneralSettings.EnablePressAnimation = true;
            windowsGeneralSettings.EnableRippleEffect = true;
            windowsGeneralSettings.EnableShadow = false;
            windowsGeneralSettings.EnableTextWrapping = false;
            windowsGeneralSettings.Font = new Font("Microsoft YaHei UI", 14.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            windowsGeneralSettings.GlowColor = Color.Cyan;
            windowsGeneralSettings.GlowIntensity = 100;
            windowsGeneralSettings.GlowRadius = 20F;
            windowsGeneralSettings.GradientBackground = false;
            windowsGeneralSettings.GradientColor = Color.FromArgb(0, 227, 64);
            windowsGeneralSettings.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            windowsGeneralSettings.HintText = null;
            windowsGeneralSettings.HoverBackColor = Color.FromArgb(50, 50, 50);
            windowsGeneralSettings.HoverFontStyle = FontStyle.Regular;
            windowsGeneralSettings.HoverTextColor = Color.White;
            windowsGeneralSettings.HoverTransitionDuration = 250;
            windowsGeneralSettings.ImageAlign = ContentAlignment.MiddleLeft;
            windowsGeneralSettings.ImagePadding = 5;
            windowsGeneralSettings.ImageSize = new Size(16, 16);
            windowsGeneralSettings.IsRadial = false;
            windowsGeneralSettings.IsReadOnly = false;
            windowsGeneralSettings.IsToggleButton = false;
            windowsGeneralSettings.IsToggled = false;
            windowsGeneralSettings.Location = new Point(12, 294);
            windowsGeneralSettings.LongPressDurationMS = 1000;
            windowsGeneralSettings.Name = "windowsGeneralSettings";
            windowsGeneralSettings.NormalFontStyle = FontStyle.Regular;
            windowsGeneralSettings.ParticleColor = Color.FromArgb(200, 200, 200);
            windowsGeneralSettings.ParticleCount = 15;
            windowsGeneralSettings.PressAnimationScale = 0.97F;
            windowsGeneralSettings.PressedBackColor = Color.FromArgb(40, 40, 40);
            windowsGeneralSettings.PressedFontStyle = FontStyle.Regular;
            windowsGeneralSettings.PressTransitionDuration = 150;
            windowsGeneralSettings.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            windowsGeneralSettings.RippleColor = Color.FromArgb(100, 100, 100);
            windowsGeneralSettings.RippleOpacity = 0.3F;
            windowsGeneralSettings.RippleRadiusMultiplier = 0.6F;
            windowsGeneralSettings.ShadowBlur = 5;
            windowsGeneralSettings.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            windowsGeneralSettings.ShadowOffset = new Point(2, 2);
            windowsGeneralSettings.ShakeDuration = 500;
            windowsGeneralSettings.ShakeIntensity = 5;
            windowsGeneralSettings.Size = new Size(270, 35);
            windowsGeneralSettings.TabIndex = 31;
            windowsGeneralSettings.Text = "Windows General Settings";
            windowsGeneralSettings.TextAlign = ContentAlignment.MiddleCenter;
            windowsGeneralSettings.TextColor = Color.White;
            windowsGeneralSettings.TooltipText = null;
            windowsGeneralSettings.UseAdvancedRendering = true;
            windowsGeneralSettings.UseParticles = false;
            windowsGeneralSettings.Click += generalWindowsSettings_Click;
            windowsGeneralSettings.MouseClick += apply;
            windowsGeneralSettings.MouseEnter += hover;
            // 
            // debloatWindows
            // 
            debloatWindows.AccessibleDescription = "";
            debloatWindows.AccessibleName = "Debloat Windows";
            debloatWindows.AutoSizeBasedOnText = false;
            debloatWindows.BackColor = Color.Transparent;
            debloatWindows.BadgeBackColor = Color.Black;
            debloatWindows.BadgeFont = new Font("Microsoft YaHei UI", 11.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            debloatWindows.BadgeValue = 0;
            debloatWindows.BadgeValueForeColor = Color.White;
            debloatWindows.BorderColor = Color.FromArgb(60, 60, 60);
            debloatWindows.BorderWidth = 2;
            debloatWindows.ButtonBackColor = Color.FromArgb(30, 30, 30);
            debloatWindows.ButtonImage = null;
            debloatWindows.ButtonTextLeftPadding = 0;
            debloatWindows.CanBeep = true;
            debloatWindows.CanGlow = true;
            debloatWindows.CanShake = true;
            debloatWindows.ContextMenuStripEx = null;
            debloatWindows.CornerRadiusBottomLeft = 6;
            debloatWindows.CornerRadiusBottomRight = 6;
            debloatWindows.CornerRadiusTopLeft = 6;
            debloatWindows.CornerRadiusTopRight = 6;
            debloatWindows.CustomCursor = Cursors.Default;
            debloatWindows.DisabledTextColor = Color.FromArgb(150, 150, 150);
            debloatWindows.EnableLongPress = false;
            debloatWindows.EnablePressAnimation = true;
            debloatWindows.EnableRippleEffect = true;
            debloatWindows.EnableShadow = false;
            debloatWindows.EnableTextWrapping = false;
            debloatWindows.Font = new Font("Microsoft YaHei UI", 14.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            debloatWindows.GlowColor = Color.Cyan;
            debloatWindows.GlowIntensity = 100;
            debloatWindows.GlowRadius = 20F;
            debloatWindows.GradientBackground = false;
            debloatWindows.GradientColor = Color.FromArgb(0, 227, 64);
            debloatWindows.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            debloatWindows.HintText = null;
            debloatWindows.HoverBackColor = Color.FromArgb(50, 50, 50);
            debloatWindows.HoverFontStyle = FontStyle.Regular;
            debloatWindows.HoverTextColor = Color.White;
            debloatWindows.HoverTransitionDuration = 250;
            debloatWindows.ImageAlign = ContentAlignment.MiddleLeft;
            debloatWindows.ImagePadding = 5;
            debloatWindows.ImageSize = new Size(16, 16);
            debloatWindows.IsRadial = false;
            debloatWindows.IsReadOnly = false;
            debloatWindows.IsToggleButton = false;
            debloatWindows.IsToggled = false;
            debloatWindows.Location = new Point(12, 335);
            debloatWindows.LongPressDurationMS = 1000;
            debloatWindows.Name = "debloatWindows";
            debloatWindows.NormalFontStyle = FontStyle.Regular;
            debloatWindows.ParticleColor = Color.FromArgb(200, 200, 200);
            debloatWindows.ParticleCount = 15;
            debloatWindows.PressAnimationScale = 0.97F;
            debloatWindows.PressedBackColor = Color.FromArgb(40, 40, 40);
            debloatWindows.PressedFontStyle = FontStyle.Regular;
            debloatWindows.PressTransitionDuration = 150;
            debloatWindows.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            debloatWindows.RippleColor = Color.FromArgb(100, 100, 100);
            debloatWindows.RippleOpacity = 0.3F;
            debloatWindows.RippleRadiusMultiplier = 0.6F;
            debloatWindows.ShadowBlur = 5;
            debloatWindows.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            debloatWindows.ShadowOffset = new Point(2, 2);
            debloatWindows.ShakeDuration = 500;
            debloatWindows.ShakeIntensity = 5;
            debloatWindows.Size = new Size(188, 35);
            debloatWindows.TabIndex = 32;
            debloatWindows.Text = "Debloat Windows";
            debloatWindows.TextAlign = ContentAlignment.MiddleCenter;
            debloatWindows.TextColor = Color.White;
            debloatWindows.TooltipText = null;
            debloatWindows.UseAdvancedRendering = true;
            debloatWindows.UseParticles = false;
            debloatWindows.Click += debloatWindows_Click;
            debloatWindows.MouseClick += apply;
            debloatWindows.MouseEnter += hover;
            // 
            // rebloat_Windows
            // 
            rebloat_Windows.AccessibleDescription = "";
            rebloat_Windows.AccessibleName = "Rebloat Windows";
            rebloat_Windows.AutoSizeBasedOnText = false;
            rebloat_Windows.BackColor = Color.Transparent;
            rebloat_Windows.BadgeBackColor = Color.Black;
            rebloat_Windows.BadgeFont = new Font("Microsoft YaHei UI", 11.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            rebloat_Windows.BadgeValue = 0;
            rebloat_Windows.BadgeValueForeColor = Color.White;
            rebloat_Windows.BorderColor = Color.FromArgb(60, 60, 60);
            rebloat_Windows.BorderWidth = 2;
            rebloat_Windows.ButtonBackColor = Color.FromArgb(30, 30, 30);
            rebloat_Windows.ButtonImage = null;
            rebloat_Windows.ButtonTextLeftPadding = 0;
            rebloat_Windows.CanBeep = true;
            rebloat_Windows.CanGlow = true;
            rebloat_Windows.CanShake = true;
            rebloat_Windows.ContextMenuStripEx = null;
            rebloat_Windows.CornerRadiusBottomLeft = 6;
            rebloat_Windows.CornerRadiusBottomRight = 6;
            rebloat_Windows.CornerRadiusTopLeft = 6;
            rebloat_Windows.CornerRadiusTopRight = 6;
            rebloat_Windows.CustomCursor = Cursors.Default;
            rebloat_Windows.DisabledTextColor = Color.FromArgb(150, 150, 150);
            rebloat_Windows.EnableLongPress = false;
            rebloat_Windows.EnablePressAnimation = true;
            rebloat_Windows.EnableRippleEffect = true;
            rebloat_Windows.EnableShadow = false;
            rebloat_Windows.EnableTextWrapping = false;
            rebloat_Windows.Font = new Font("Microsoft YaHei UI", 14.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            rebloat_Windows.GlowColor = Color.Cyan;
            rebloat_Windows.GlowIntensity = 100;
            rebloat_Windows.GlowRadius = 20F;
            rebloat_Windows.GradientBackground = false;
            rebloat_Windows.GradientColor = Color.FromArgb(0, 227, 64);
            rebloat_Windows.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            rebloat_Windows.HintText = null;
            rebloat_Windows.HoverBackColor = Color.FromArgb(50, 50, 50);
            rebloat_Windows.HoverFontStyle = FontStyle.Regular;
            rebloat_Windows.HoverTextColor = Color.White;
            rebloat_Windows.HoverTransitionDuration = 250;
            rebloat_Windows.ImageAlign = ContentAlignment.MiddleLeft;
            rebloat_Windows.ImagePadding = 5;
            rebloat_Windows.ImageSize = new Size(16, 16);
            rebloat_Windows.IsRadial = false;
            rebloat_Windows.IsReadOnly = false;
            rebloat_Windows.IsToggleButton = false;
            rebloat_Windows.IsToggled = false;
            rebloat_Windows.Location = new Point(12, 376);
            rebloat_Windows.LongPressDurationMS = 1000;
            rebloat_Windows.Name = "rebloat_Windows";
            rebloat_Windows.NormalFontStyle = FontStyle.Regular;
            rebloat_Windows.ParticleColor = Color.FromArgb(200, 200, 200);
            rebloat_Windows.ParticleCount = 15;
            rebloat_Windows.PressAnimationScale = 0.97F;
            rebloat_Windows.PressedBackColor = Color.FromArgb(40, 40, 40);
            rebloat_Windows.PressedFontStyle = FontStyle.Regular;
            rebloat_Windows.PressTransitionDuration = 150;
            rebloat_Windows.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            rebloat_Windows.RippleColor = Color.FromArgb(100, 100, 100);
            rebloat_Windows.RippleOpacity = 0.3F;
            rebloat_Windows.RippleRadiusMultiplier = 0.6F;
            rebloat_Windows.ShadowBlur = 5;
            rebloat_Windows.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            rebloat_Windows.ShadowOffset = new Point(2, 2);
            rebloat_Windows.ShakeDuration = 500;
            rebloat_Windows.ShakeIntensity = 5;
            rebloat_Windows.Size = new Size(188, 35);
            rebloat_Windows.TabIndex = 33;
            rebloat_Windows.Text = "Rebloat Windows";
            rebloat_Windows.TextAlign = ContentAlignment.MiddleCenter;
            rebloat_Windows.TextColor = Color.White;
            rebloat_Windows.TooltipText = null;
            rebloat_Windows.UseAdvancedRendering = true;
            rebloat_Windows.UseParticles = false;
            rebloat_Windows.Click += rebloatWindows_Click;
            rebloat_Windows.MouseClick += apply;
            rebloat_Windows.MouseEnter += hover;
            // 
            // debloatStartup
            // 
            debloatStartup.AccessibleDescription = "";
            debloatStartup.AccessibleName = "Debloat Startup Applications";
            debloatStartup.AutoSizeBasedOnText = false;
            debloatStartup.BackColor = Color.Transparent;
            debloatStartup.BadgeBackColor = Color.Black;
            debloatStartup.BadgeFont = new Font("Microsoft YaHei UI", 11.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            debloatStartup.BadgeValue = 0;
            debloatStartup.BadgeValueForeColor = Color.White;
            debloatStartup.BorderColor = Color.FromArgb(60, 60, 60);
            debloatStartup.BorderWidth = 2;
            debloatStartup.ButtonBackColor = Color.FromArgb(30, 30, 30);
            debloatStartup.ButtonImage = null;
            debloatStartup.ButtonTextLeftPadding = 0;
            debloatStartup.CanBeep = true;
            debloatStartup.CanGlow = true;
            debloatStartup.CanShake = true;
            debloatStartup.ContextMenuStripEx = null;
            debloatStartup.CornerRadiusBottomLeft = 6;
            debloatStartup.CornerRadiusBottomRight = 6;
            debloatStartup.CornerRadiusTopLeft = 6;
            debloatStartup.CornerRadiusTopRight = 6;
            debloatStartup.CustomCursor = Cursors.Default;
            debloatStartup.DisabledTextColor = Color.FromArgb(150, 150, 150);
            debloatStartup.EnableLongPress = false;
            debloatStartup.EnablePressAnimation = true;
            debloatStartup.EnableRippleEffect = true;
            debloatStartup.EnableShadow = false;
            debloatStartup.EnableTextWrapping = false;
            debloatStartup.Font = new Font("Microsoft YaHei UI", 14.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            debloatStartup.GlowColor = Color.Cyan;
            debloatStartup.GlowIntensity = 100;
            debloatStartup.GlowRadius = 20F;
            debloatStartup.GradientBackground = false;
            debloatStartup.GradientColor = Color.FromArgb(0, 227, 64);
            debloatStartup.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            debloatStartup.HintText = null;
            debloatStartup.HoverBackColor = Color.FromArgb(50, 50, 50);
            debloatStartup.HoverFontStyle = FontStyle.Regular;
            debloatStartup.HoverTextColor = Color.White;
            debloatStartup.HoverTransitionDuration = 250;
            debloatStartup.ImageAlign = ContentAlignment.MiddleLeft;
            debloatStartup.ImagePadding = 5;
            debloatStartup.ImageSize = new Size(16, 16);
            debloatStartup.IsRadial = false;
            debloatStartup.IsReadOnly = false;
            debloatStartup.IsToggleButton = false;
            debloatStartup.IsToggled = false;
            debloatStartup.Location = new Point(12, 417);
            debloatStartup.LongPressDurationMS = 1000;
            debloatStartup.Name = "debloatStartup";
            debloatStartup.NormalFontStyle = FontStyle.Regular;
            debloatStartup.ParticleColor = Color.FromArgb(200, 200, 200);
            debloatStartup.ParticleCount = 15;
            debloatStartup.PressAnimationScale = 0.97F;
            debloatStartup.PressedBackColor = Color.FromArgb(40, 40, 40);
            debloatStartup.PressedFontStyle = FontStyle.Regular;
            debloatStartup.PressTransitionDuration = 150;
            debloatStartup.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            debloatStartup.RippleColor = Color.FromArgb(100, 100, 100);
            debloatStartup.RippleOpacity = 0.3F;
            debloatStartup.RippleRadiusMultiplier = 0.6F;
            debloatStartup.ShadowBlur = 5;
            debloatStartup.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            debloatStartup.ShadowOffset = new Point(2, 2);
            debloatStartup.ShakeDuration = 500;
            debloatStartup.ShakeIntensity = 5;
            debloatStartup.Size = new Size(298, 35);
            debloatStartup.TabIndex = 34;
            debloatStartup.Text = "Debloat Startup Applications";
            debloatStartup.TextAlign = ContentAlignment.MiddleCenter;
            debloatStartup.TextColor = Color.White;
            debloatStartup.TooltipText = null;
            debloatStartup.UseAdvancedRendering = true;
            debloatStartup.UseParticles = false;
            debloatStartup.Click += debloatStartup_Click;
            debloatStartup.MouseClick += apply;
            debloatStartup.MouseEnter += hover;
            // 
            // i
            // 
            i.AccessibleDescription = "";
            i.AccessibleName = "i";
            i.AutoSizeBasedOnText = false;
            i.BackColor = Color.Transparent;
            i.BadgeBackColor = Color.Black;
            i.BadgeFont = new Font("Microsoft YaHei UI", 11.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            i.BadgeValue = 0;
            i.BadgeValueForeColor = Color.White;
            i.BorderColor = Color.Cyan;
            i.BorderWidth = 2;
            i.ButtonBackColor = Color.FromArgb(30, 30, 30);
            i.ButtonImage = null;
            i.ButtonTextLeftPadding = 0;
            i.CanBeep = true;
            i.CanGlow = true;
            i.CanShake = true;
            i.ContextMenuStripEx = null;
            i.CornerRadiusBottomLeft = 6;
            i.CornerRadiusBottomRight = 6;
            i.CornerRadiusTopLeft = 6;
            i.CornerRadiusTopRight = 6;
            i.CustomCursor = Cursors.Default;
            i.DisabledTextColor = Color.FromArgb(150, 150, 150);
            i.EnableLongPress = false;
            i.EnablePressAnimation = true;
            i.EnableRippleEffect = true;
            i.EnableShadow = false;
            i.EnableTextWrapping = false;
            i.Font = new Font("Microsoft YaHei UI", 14.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            i.GlowColor = Color.Cyan;
            i.GlowIntensity = 100;
            i.GlowRadius = 20F;
            i.GradientBackground = false;
            i.GradientColor = Color.FromArgb(0, 227, 64);
            i.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            i.HintText = null;
            i.HoverBackColor = Color.FromArgb(50, 50, 50);
            i.HoverFontStyle = FontStyle.Regular;
            i.HoverTextColor = Color.White;
            i.HoverTransitionDuration = 250;
            i.ImageAlign = ContentAlignment.MiddleLeft;
            i.ImagePadding = 5;
            i.ImageSize = new Size(16, 16);
            i.IsRadial = false;
            i.IsReadOnly = false;
            i.IsToggleButton = false;
            i.IsToggled = false;
            i.Location = new Point(214, 335);
            i.LongPressDurationMS = 1000;
            i.Name = "i";
            i.NormalFontStyle = FontStyle.Regular;
            i.ParticleColor = Color.FromArgb(200, 200, 200);
            i.ParticleCount = 15;
            i.PressAnimationScale = 0.97F;
            i.PressedBackColor = Color.FromArgb(40, 40, 40);
            i.PressedFontStyle = FontStyle.Regular;
            i.PressTransitionDuration = 150;
            i.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            i.RippleColor = Color.FromArgb(100, 100, 100);
            i.RippleOpacity = 0.3F;
            i.RippleRadiusMultiplier = 0.6F;
            i.ShadowBlur = 5;
            i.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            i.ShadowOffset = new Point(2, 2);
            i.ShakeDuration = 500;
            i.ShakeIntensity = 5;
            i.Size = new Size(21, 35);
            i.TabIndex = 35;
            i.Text = "i";
            i.TextAlign = ContentAlignment.MiddleCenter;
            i.TextColor = Color.White;
            i.TooltipText = null;
            i.UseAdvancedRendering = true;
            i.UseParticles = false;
            i.Click += i_Click;
            i.MouseClick += apply;
            i.MouseEnter += hover;
            // 
            // i2
            // 
            i2.AccessibleDescription = "";
            i2.AccessibleName = "i";
            i2.AutoSizeBasedOnText = false;
            i2.BackColor = Color.Transparent;
            i2.BadgeBackColor = Color.Black;
            i2.BadgeFont = new Font("Microsoft YaHei UI", 11.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            i2.BadgeValue = 0;
            i2.BadgeValueForeColor = Color.White;
            i2.BorderColor = Color.Cyan;
            i2.BorderWidth = 2;
            i2.ButtonBackColor = Color.FromArgb(30, 30, 30);
            i2.ButtonImage = null;
            i2.ButtonTextLeftPadding = 0;
            i2.CanBeep = true;
            i2.CanGlow = true;
            i2.CanShake = true;
            i2.ContextMenuStripEx = null;
            i2.CornerRadiusBottomLeft = 6;
            i2.CornerRadiusBottomRight = 6;
            i2.CornerRadiusTopLeft = 6;
            i2.CornerRadiusTopRight = 6;
            i2.CustomCursor = Cursors.Default;
            i2.DisabledTextColor = Color.FromArgb(150, 150, 150);
            i2.EnableLongPress = false;
            i2.EnablePressAnimation = true;
            i2.EnableRippleEffect = true;
            i2.EnableShadow = false;
            i2.EnableTextWrapping = false;
            i2.Font = new Font("Microsoft YaHei UI", 14.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            i2.GlowColor = Color.Cyan;
            i2.GlowIntensity = 100;
            i2.GlowRadius = 20F;
            i2.GradientBackground = false;
            i2.GradientColor = Color.FromArgb(0, 227, 64);
            i2.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            i2.HintText = null;
            i2.HoverBackColor = Color.FromArgb(50, 50, 50);
            i2.HoverFontStyle = FontStyle.Regular;
            i2.HoverTextColor = Color.White;
            i2.HoverTransitionDuration = 250;
            i2.ImageAlign = ContentAlignment.MiddleLeft;
            i2.ImagePadding = 5;
            i2.ImageSize = new Size(16, 16);
            i2.IsRadial = false;
            i2.IsReadOnly = false;
            i2.IsToggleButton = false;
            i2.IsToggled = false;
            i2.Location = new Point(214, 376);
            i2.LongPressDurationMS = 1000;
            i2.Name = "i2";
            i2.NormalFontStyle = FontStyle.Regular;
            i2.ParticleColor = Color.FromArgb(200, 200, 200);
            i2.ParticleCount = 15;
            i2.PressAnimationScale = 0.97F;
            i2.PressedBackColor = Color.FromArgb(40, 40, 40);
            i2.PressedFontStyle = FontStyle.Regular;
            i2.PressTransitionDuration = 150;
            i2.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            i2.RippleColor = Color.FromArgb(100, 100, 100);
            i2.RippleOpacity = 0.3F;
            i2.RippleRadiusMultiplier = 0.6F;
            i2.ShadowBlur = 5;
            i2.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            i2.ShadowOffset = new Point(2, 2);
            i2.ShakeDuration = 500;
            i2.ShakeIntensity = 5;
            i2.Size = new Size(21, 35);
            i2.TabIndex = 36;
            i2.Text = "i";
            i2.TextAlign = ContentAlignment.MiddleCenter;
            i2.TextColor = Color.White;
            i2.TooltipText = null;
            i2.UseAdvancedRendering = true;
            i2.UseParticles = false;
            i2.Click += i2_Click;
            i2.MouseClick += apply;
            i2.MouseEnter += hover;
            // 
            // cpuTweaks
            // 
            cpuTweaks.AccessibleDescription = "";
            cpuTweaks.AccessibleName = "CPU Tweaks";
            cpuTweaks.AutoSizeBasedOnText = false;
            cpuTweaks.BackColor = Color.Transparent;
            cpuTweaks.BadgeBackColor = Color.Black;
            cpuTweaks.BadgeFont = new Font("Microsoft YaHei UI", 11.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            cpuTweaks.BadgeValue = 0;
            cpuTweaks.BadgeValueForeColor = Color.White;
            cpuTweaks.BorderColor = Color.FromArgb(60, 60, 60);
            cpuTweaks.BorderWidth = 2;
            cpuTweaks.ButtonBackColor = Color.FromArgb(30, 30, 30);
            cpuTweaks.ButtonImage = null;
            cpuTweaks.ButtonTextLeftPadding = 0;
            cpuTweaks.CanBeep = true;
            cpuTweaks.CanGlow = true;
            cpuTweaks.CanShake = true;
            cpuTweaks.ContextMenuStripEx = null;
            cpuTweaks.CornerRadiusBottomLeft = 6;
            cpuTweaks.CornerRadiusBottomRight = 6;
            cpuTweaks.CornerRadiusTopLeft = 6;
            cpuTweaks.CornerRadiusTopRight = 6;
            cpuTweaks.CustomCursor = Cursors.Default;
            cpuTweaks.DisabledTextColor = Color.FromArgb(150, 150, 150);
            cpuTweaks.EnableLongPress = false;
            cpuTweaks.EnablePressAnimation = true;
            cpuTweaks.EnableRippleEffect = true;
            cpuTweaks.EnableShadow = false;
            cpuTweaks.EnableTextWrapping = false;
            cpuTweaks.Font = new Font("Microsoft YaHei UI", 14.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            cpuTweaks.GlowColor = Color.Cyan;
            cpuTweaks.GlowIntensity = 100;
            cpuTweaks.GlowRadius = 20F;
            cpuTweaks.GradientBackground = false;
            cpuTweaks.GradientColor = Color.FromArgb(0, 227, 64);
            cpuTweaks.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            cpuTweaks.HintText = null;
            cpuTweaks.HoverBackColor = Color.FromArgb(50, 50, 50);
            cpuTweaks.HoverFontStyle = FontStyle.Regular;
            cpuTweaks.HoverTextColor = Color.White;
            cpuTweaks.HoverTransitionDuration = 250;
            cpuTweaks.ImageAlign = ContentAlignment.MiddleLeft;
            cpuTweaks.ImagePadding = 5;
            cpuTweaks.ImageSize = new Size(16, 16);
            cpuTweaks.IsRadial = false;
            cpuTweaks.IsReadOnly = false;
            cpuTweaks.IsToggleButton = false;
            cpuTweaks.IsToggled = false;
            cpuTweaks.Location = new Point(12, 458);
            cpuTweaks.LongPressDurationMS = 1000;
            cpuTweaks.Name = "cpuTweaks";
            cpuTweaks.NormalFontStyle = FontStyle.Regular;
            cpuTweaks.ParticleColor = Color.FromArgb(200, 200, 200);
            cpuTweaks.ParticleCount = 15;
            cpuTweaks.PressAnimationScale = 0.97F;
            cpuTweaks.PressedBackColor = Color.FromArgb(40, 40, 40);
            cpuTweaks.PressedFontStyle = FontStyle.Regular;
            cpuTweaks.PressTransitionDuration = 150;
            cpuTweaks.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            cpuTweaks.RippleColor = Color.FromArgb(100, 100, 100);
            cpuTweaks.RippleOpacity = 0.3F;
            cpuTweaks.RippleRadiusMultiplier = 0.6F;
            cpuTweaks.ShadowBlur = 5;
            cpuTweaks.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            cpuTweaks.ShadowOffset = new Point(2, 2);
            cpuTweaks.ShakeDuration = 500;
            cpuTweaks.ShakeIntensity = 5;
            cpuTweaks.Size = new Size(131, 35);
            cpuTweaks.TabIndex = 37;
            cpuTweaks.Text = "CPU Tweaks";
            cpuTweaks.TextAlign = ContentAlignment.MiddleCenter;
            cpuTweaks.TextColor = Color.White;
            cpuTweaks.TooltipText = null;
            cpuTweaks.UseAdvancedRendering = true;
            cpuTweaks.UseParticles = false;
            cpuTweaks.Click += cpuTweaks_Click;
            cpuTweaks.MouseClick += apply;
            cpuTweaks.MouseEnter += hover;
            // 
            // cleanTempFiles
            // 
            cleanTempFiles.AccessibleDescription = "";
            cleanTempFiles.AccessibleName = "Clean Temp Files";
            cleanTempFiles.AutoSizeBasedOnText = false;
            cleanTempFiles.BackColor = Color.Transparent;
            cleanTempFiles.BadgeBackColor = Color.Black;
            cleanTempFiles.BadgeFont = new Font("Microsoft YaHei UI", 11.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            cleanTempFiles.BadgeValue = 0;
            cleanTempFiles.BadgeValueForeColor = Color.White;
            cleanTempFiles.BorderColor = Color.FromArgb(60, 60, 60);
            cleanTempFiles.BorderWidth = 2;
            cleanTempFiles.ButtonBackColor = Color.FromArgb(30, 30, 30);
            cleanTempFiles.ButtonImage = null;
            cleanTempFiles.ButtonTextLeftPadding = 0;
            cleanTempFiles.CanBeep = true;
            cleanTempFiles.CanGlow = true;
            cleanTempFiles.CanShake = true;
            cleanTempFiles.ContextMenuStripEx = null;
            cleanTempFiles.CornerRadiusBottomLeft = 6;
            cleanTempFiles.CornerRadiusBottomRight = 6;
            cleanTempFiles.CornerRadiusTopLeft = 6;
            cleanTempFiles.CornerRadiusTopRight = 6;
            cleanTempFiles.CustomCursor = Cursors.Default;
            cleanTempFiles.DisabledTextColor = Color.FromArgb(150, 150, 150);
            cleanTempFiles.EnableLongPress = false;
            cleanTempFiles.EnablePressAnimation = true;
            cleanTempFiles.EnableRippleEffect = true;
            cleanTempFiles.EnableShadow = false;
            cleanTempFiles.EnableTextWrapping = false;
            cleanTempFiles.Font = new Font("Microsoft YaHei UI", 14.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            cleanTempFiles.GlowColor = Color.Cyan;
            cleanTempFiles.GlowIntensity = 100;
            cleanTempFiles.GlowRadius = 20F;
            cleanTempFiles.GradientBackground = false;
            cleanTempFiles.GradientColor = Color.FromArgb(0, 227, 64);
            cleanTempFiles.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            cleanTempFiles.HintText = null;
            cleanTempFiles.HoverBackColor = Color.FromArgb(50, 50, 50);
            cleanTempFiles.HoverFontStyle = FontStyle.Regular;
            cleanTempFiles.HoverTextColor = Color.White;
            cleanTempFiles.HoverTransitionDuration = 250;
            cleanTempFiles.ImageAlign = ContentAlignment.MiddleLeft;
            cleanTempFiles.ImagePadding = 5;
            cleanTempFiles.ImageSize = new Size(16, 16);
            cleanTempFiles.IsRadial = false;
            cleanTempFiles.IsReadOnly = false;
            cleanTempFiles.IsToggleButton = false;
            cleanTempFiles.IsToggled = false;
            cleanTempFiles.Location = new Point(12, 499);
            cleanTempFiles.LongPressDurationMS = 1000;
            cleanTempFiles.Name = "cleanTempFiles";
            cleanTempFiles.NormalFontStyle = FontStyle.Regular;
            cleanTempFiles.ParticleColor = Color.FromArgb(200, 200, 200);
            cleanTempFiles.ParticleCount = 15;
            cleanTempFiles.PressAnimationScale = 0.97F;
            cleanTempFiles.PressedBackColor = Color.FromArgb(40, 40, 40);
            cleanTempFiles.PressedFontStyle = FontStyle.Regular;
            cleanTempFiles.PressTransitionDuration = 150;
            cleanTempFiles.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            cleanTempFiles.RippleColor = Color.FromArgb(100, 100, 100);
            cleanTempFiles.RippleOpacity = 0.3F;
            cleanTempFiles.RippleRadiusMultiplier = 0.6F;
            cleanTempFiles.ShadowBlur = 5;
            cleanTempFiles.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            cleanTempFiles.ShadowOffset = new Point(2, 2);
            cleanTempFiles.ShakeDuration = 500;
            cleanTempFiles.ShakeIntensity = 5;
            cleanTempFiles.Size = new Size(177, 35);
            cleanTempFiles.TabIndex = 38;
            cleanTempFiles.Text = "Clean Temp Files";
            cleanTempFiles.TextAlign = ContentAlignment.MiddleCenter;
            cleanTempFiles.TextColor = Color.White;
            cleanTempFiles.TooltipText = null;
            cleanTempFiles.UseAdvancedRendering = true;
            cleanTempFiles.UseParticles = false;
            cleanTempFiles.Click += cleanTempFiles_Click;
            cleanTempFiles.MouseClick += apply;
            cleanTempFiles.MouseEnter += hover;
            // 
            // menuKillTime
            // 
            menuKillTime.AccessibleDescription = "";
            menuKillTime.AccessibleName = "Menu Kill Time";
            menuKillTime.AutoSizeBasedOnText = false;
            menuKillTime.BackColor = Color.Transparent;
            menuKillTime.BadgeBackColor = Color.Black;
            menuKillTime.BadgeFont = new Font("Microsoft YaHei UI", 11.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            menuKillTime.BadgeValue = 0;
            menuKillTime.BadgeValueForeColor = Color.White;
            menuKillTime.BorderColor = Color.FromArgb(60, 60, 60);
            menuKillTime.BorderWidth = 2;
            menuKillTime.ButtonBackColor = Color.FromArgb(30, 30, 30);
            menuKillTime.ButtonImage = null;
            menuKillTime.ButtonTextLeftPadding = 0;
            menuKillTime.CanBeep = true;
            menuKillTime.CanGlow = true;
            menuKillTime.CanShake = true;
            menuKillTime.ContextMenuStripEx = null;
            menuKillTime.CornerRadiusBottomLeft = 6;
            menuKillTime.CornerRadiusBottomRight = 6;
            menuKillTime.CornerRadiusTopLeft = 6;
            menuKillTime.CornerRadiusTopRight = 6;
            menuKillTime.CustomCursor = Cursors.Default;
            menuKillTime.DisabledTextColor = Color.FromArgb(150, 150, 150);
            menuKillTime.EnableLongPress = false;
            menuKillTime.EnablePressAnimation = true;
            menuKillTime.EnableRippleEffect = true;
            menuKillTime.EnableShadow = false;
            menuKillTime.EnableTextWrapping = false;
            menuKillTime.Font = new Font("Microsoft YaHei UI", 14.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            menuKillTime.GlowColor = Color.Cyan;
            menuKillTime.GlowIntensity = 100;
            menuKillTime.GlowRadius = 20F;
            menuKillTime.GradientBackground = false;
            menuKillTime.GradientColor = Color.FromArgb(0, 227, 64);
            menuKillTime.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            menuKillTime.HintText = null;
            menuKillTime.HoverBackColor = Color.FromArgb(50, 50, 50);
            menuKillTime.HoverFontStyle = FontStyle.Regular;
            menuKillTime.HoverTextColor = Color.White;
            menuKillTime.HoverTransitionDuration = 250;
            menuKillTime.ImageAlign = ContentAlignment.MiddleLeft;
            menuKillTime.ImagePadding = 5;
            menuKillTime.ImageSize = new Size(16, 16);
            menuKillTime.IsRadial = false;
            menuKillTime.IsReadOnly = false;
            menuKillTime.IsToggleButton = false;
            menuKillTime.IsToggled = false;
            menuKillTime.Location = new Point(12, 540);
            menuKillTime.LongPressDurationMS = 1000;
            menuKillTime.Name = "menuKillTime";
            menuKillTime.NormalFontStyle = FontStyle.Regular;
            menuKillTime.ParticleColor = Color.FromArgb(200, 200, 200);
            menuKillTime.ParticleCount = 15;
            menuKillTime.PressAnimationScale = 0.97F;
            menuKillTime.PressedBackColor = Color.FromArgb(40, 40, 40);
            menuKillTime.PressedFontStyle = FontStyle.Regular;
            menuKillTime.PressTransitionDuration = 150;
            menuKillTime.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            menuKillTime.RippleColor = Color.FromArgb(100, 100, 100);
            menuKillTime.RippleOpacity = 0.3F;
            menuKillTime.RippleRadiusMultiplier = 0.6F;
            menuKillTime.ShadowBlur = 5;
            menuKillTime.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            menuKillTime.ShadowOffset = new Point(2, 2);
            menuKillTime.ShakeDuration = 500;
            menuKillTime.ShakeIntensity = 5;
            menuKillTime.Size = new Size(159, 35);
            menuKillTime.TabIndex = 39;
            menuKillTime.Text = "Menu Kill Time";
            menuKillTime.TextAlign = ContentAlignment.MiddleCenter;
            menuKillTime.TextColor = Color.White;
            menuKillTime.TooltipText = null;
            menuKillTime.UseAdvancedRendering = true;
            menuKillTime.UseParticles = false;
            menuKillTime.Click += menuKillTime_Click;
            menuKillTime.MouseClick += apply;
            menuKillTime.MouseEnter += hover;
            // 
            // msiUtlity
            // 
            msiUtlity.AccessibleDescription = "";
            msiUtlity.AccessibleName = "MSI Utlity";
            msiUtlity.AutoSizeBasedOnText = false;
            msiUtlity.BackColor = Color.Transparent;
            msiUtlity.BadgeBackColor = Color.Black;
            msiUtlity.BadgeFont = new Font("Microsoft YaHei UI", 11.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            msiUtlity.BadgeValue = 0;
            msiUtlity.BadgeValueForeColor = Color.White;
            msiUtlity.BorderColor = Color.FromArgb(60, 60, 60);
            msiUtlity.BorderWidth = 2;
            msiUtlity.ButtonBackColor = Color.FromArgb(30, 30, 30);
            msiUtlity.ButtonImage = null;
            msiUtlity.ButtonTextLeftPadding = 0;
            msiUtlity.CanBeep = true;
            msiUtlity.CanGlow = true;
            msiUtlity.CanShake = true;
            msiUtlity.ContextMenuStripEx = null;
            msiUtlity.CornerRadiusBottomLeft = 6;
            msiUtlity.CornerRadiusBottomRight = 6;
            msiUtlity.CornerRadiusTopLeft = 6;
            msiUtlity.CornerRadiusTopRight = 6;
            msiUtlity.CustomCursor = Cursors.Default;
            msiUtlity.DisabledTextColor = Color.FromArgb(150, 150, 150);
            msiUtlity.EnableLongPress = false;
            msiUtlity.EnablePressAnimation = true;
            msiUtlity.EnableRippleEffect = true;
            msiUtlity.EnableShadow = false;
            msiUtlity.EnableTextWrapping = false;
            msiUtlity.Font = new Font("Microsoft YaHei UI", 14.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            msiUtlity.GlowColor = Color.Cyan;
            msiUtlity.GlowIntensity = 100;
            msiUtlity.GlowRadius = 20F;
            msiUtlity.GradientBackground = false;
            msiUtlity.GradientColor = Color.FromArgb(0, 227, 64);
            msiUtlity.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            msiUtlity.HintText = null;
            msiUtlity.HoverBackColor = Color.FromArgb(50, 50, 50);
            msiUtlity.HoverFontStyle = FontStyle.Regular;
            msiUtlity.HoverTextColor = Color.White;
            msiUtlity.HoverTransitionDuration = 250;
            msiUtlity.ImageAlign = ContentAlignment.MiddleLeft;
            msiUtlity.ImagePadding = 5;
            msiUtlity.ImageSize = new Size(16, 16);
            msiUtlity.IsRadial = false;
            msiUtlity.IsReadOnly = false;
            msiUtlity.IsToggleButton = false;
            msiUtlity.IsToggled = false;
            msiUtlity.Location = new Point(12, 581);
            msiUtlity.LongPressDurationMS = 1000;
            msiUtlity.Name = "msiUtlity";
            msiUtlity.NormalFontStyle = FontStyle.Regular;
            msiUtlity.ParticleColor = Color.FromArgb(200, 200, 200);
            msiUtlity.ParticleCount = 15;
            msiUtlity.PressAnimationScale = 0.97F;
            msiUtlity.PressedBackColor = Color.FromArgb(40, 40, 40);
            msiUtlity.PressedFontStyle = FontStyle.Regular;
            msiUtlity.PressTransitionDuration = 150;
            msiUtlity.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            msiUtlity.RippleColor = Color.FromArgb(100, 100, 100);
            msiUtlity.RippleOpacity = 0.3F;
            msiUtlity.RippleRadiusMultiplier = 0.6F;
            msiUtlity.ShadowBlur = 5;
            msiUtlity.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            msiUtlity.ShadowOffset = new Point(2, 2);
            msiUtlity.ShakeDuration = 500;
            msiUtlity.ShakeIntensity = 5;
            msiUtlity.Size = new Size(110, 35);
            msiUtlity.TabIndex = 40;
            msiUtlity.Text = "MSI Utlity";
            msiUtlity.TextAlign = ContentAlignment.MiddleCenter;
            msiUtlity.TextColor = Color.White;
            msiUtlity.TooltipText = null;
            msiUtlity.UseAdvancedRendering = true;
            msiUtlity.UseParticles = false;
            msiUtlity.Click += msiUtlity_Click;
            msiUtlity.MouseClick += apply;
            msiUtlity.MouseEnter += hover;
            // 
            // back
            // 
            back.AccessibleDescription = "";
            back.AccessibleName = "BACK";
            back.AutoSizeBasedOnText = false;
            back.BackColor = Color.Transparent;
            back.BadgeBackColor = Color.Black;
            back.BadgeFont = new Font("Microsoft YaHei UI", 11.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            back.BadgeValue = 0;
            back.BadgeValueForeColor = Color.White;
            back.BorderColor = Color.FromArgb(60, 60, 60);
            back.BorderWidth = 2;
            back.ButtonBackColor = Color.Red;
            back.ButtonImage = null;
            back.ButtonTextLeftPadding = 0;
            back.CanBeep = true;
            back.CanGlow = true;
            back.CanShake = true;
            back.ContextMenuStripEx = null;
            back.CornerRadiusBottomLeft = 6;
            back.CornerRadiusBottomRight = 6;
            back.CornerRadiusTopLeft = 6;
            back.CornerRadiusTopRight = 6;
            back.CustomCursor = Cursors.Default;
            back.DisabledTextColor = Color.FromArgb(150, 150, 150);
            back.EnableLongPress = false;
            back.EnablePressAnimation = true;
            back.EnableRippleEffect = true;
            back.EnableShadow = false;
            back.EnableTextWrapping = false;
            back.Font = new Font("Microsoft YaHei UI", 14.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            back.GlowColor = Color.Cyan;
            back.GlowIntensity = 100;
            back.GlowRadius = 20F;
            back.GradientBackground = false;
            back.GradientColor = Color.FromArgb(0, 227, 64);
            back.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            back.HintText = null;
            back.HoverBackColor = Color.FromArgb(50, 50, 50);
            back.HoverFontStyle = FontStyle.Regular;
            back.HoverTextColor = Color.White;
            back.HoverTransitionDuration = 250;
            back.ImageAlign = ContentAlignment.MiddleLeft;
            back.ImagePadding = 5;
            back.ImageSize = new Size(16, 16);
            back.IsRadial = false;
            back.IsReadOnly = false;
            back.IsToggleButton = false;
            back.IsToggled = false;
            back.Location = new Point(910, 647);
            back.LongPressDurationMS = 1000;
            back.Name = "back";
            back.NormalFontStyle = FontStyle.Regular;
            back.ParticleColor = Color.FromArgb(200, 200, 200);
            back.ParticleCount = 15;
            back.PressAnimationScale = 0.97F;
            back.PressedBackColor = Color.FromArgb(40, 40, 40);
            back.PressedFontStyle = FontStyle.Regular;
            back.PressTransitionDuration = 150;
            back.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            back.RippleColor = Color.FromArgb(100, 100, 100);
            back.RippleOpacity = 0.3F;
            back.RippleRadiusMultiplier = 0.6F;
            back.ShadowBlur = 5;
            back.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            back.ShadowOffset = new Point(2, 2);
            back.ShakeDuration = 500;
            back.ShakeIntensity = 5;
            back.Size = new Size(71, 35);
            back.TabIndex = 41;
            back.Text = "BACK";
            back.TextAlign = ContentAlignment.MiddleCenter;
            back.TextColor = Color.White;
            back.TooltipText = null;
            back.UseAdvancedRendering = true;
            back.UseParticles = false;
            back.Click += back_Click;
            back.MouseClick += apply;
            back.MouseEnter += hover;
            // 
            // warrning
            // 
            warrning.AutoSize = true;
            warrning.Font = new Font("Microsoft YaHei UI", 8.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            warrning.ForeColor = Color.Red;
            warrning.Location = new Point(539, 171);
            warrning.Name = "warrning";
            warrning.Size = new Size(451, 80);
            warrning.TabIndex = 42;
            warrning.Text = resources.GetString("warrning.Text");
            // 
            // createRestorePoint
            // 
            createRestorePoint.AccessibleDescription = "";
            createRestorePoint.AccessibleName = "Create Restore Point";
            createRestorePoint.AutoSizeBasedOnText = false;
            createRestorePoint.BackColor = Color.Transparent;
            createRestorePoint.BadgeBackColor = Color.Black;
            createRestorePoint.BadgeFont = new Font("Microsoft YaHei UI", 11.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            createRestorePoint.BadgeValue = 0;
            createRestorePoint.BadgeValueForeColor = Color.White;
            createRestorePoint.BorderColor = Color.FromArgb(60, 60, 60);
            createRestorePoint.BorderWidth = 2;
            createRestorePoint.ButtonBackColor = Color.FromArgb(30, 30, 30);
            createRestorePoint.ButtonImage = null;
            createRestorePoint.ButtonTextLeftPadding = 0;
            createRestorePoint.CanBeep = true;
            createRestorePoint.CanGlow = true;
            createRestorePoint.CanShake = true;
            createRestorePoint.ContextMenuStripEx = null;
            createRestorePoint.CornerRadiusBottomLeft = 6;
            createRestorePoint.CornerRadiusBottomRight = 6;
            createRestorePoint.CornerRadiusTopLeft = 6;
            createRestorePoint.CornerRadiusTopRight = 6;
            createRestorePoint.CustomCursor = Cursors.Default;
            createRestorePoint.DisabledTextColor = Color.FromArgb(150, 150, 150);
            createRestorePoint.EnableLongPress = false;
            createRestorePoint.EnablePressAnimation = true;
            createRestorePoint.EnableRippleEffect = true;
            createRestorePoint.EnableShadow = false;
            createRestorePoint.EnableTextWrapping = false;
            createRestorePoint.Font = new Font("Microsoft YaHei UI", 14.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            createRestorePoint.GlowColor = Color.Cyan;
            createRestorePoint.GlowIntensity = 100;
            createRestorePoint.GlowRadius = 20F;
            createRestorePoint.GradientBackground = false;
            createRestorePoint.GradientColor = Color.FromArgb(0, 227, 64);
            createRestorePoint.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            createRestorePoint.HintText = null;
            createRestorePoint.HoverBackColor = Color.FromArgb(50, 50, 50);
            createRestorePoint.HoverFontStyle = FontStyle.Regular;
            createRestorePoint.HoverTextColor = Color.White;
            createRestorePoint.HoverTransitionDuration = 250;
            createRestorePoint.ImageAlign = ContentAlignment.MiddleLeft;
            createRestorePoint.ImagePadding = 5;
            createRestorePoint.ImageSize = new Size(16, 16);
            createRestorePoint.IsRadial = false;
            createRestorePoint.IsReadOnly = false;
            createRestorePoint.IsToggleButton = false;
            createRestorePoint.IsToggled = false;
            createRestorePoint.Location = new Point(749, 254);
            createRestorePoint.LongPressDurationMS = 1000;
            createRestorePoint.Name = "createRestorePoint";
            createRestorePoint.NormalFontStyle = FontStyle.Regular;
            createRestorePoint.ParticleColor = Color.FromArgb(200, 200, 200);
            createRestorePoint.ParticleCount = 15;
            createRestorePoint.PressAnimationScale = 0.97F;
            createRestorePoint.PressedBackColor = Color.FromArgb(40, 40, 40);
            createRestorePoint.PressedFontStyle = FontStyle.Regular;
            createRestorePoint.PressTransitionDuration = 150;
            createRestorePoint.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            createRestorePoint.RippleColor = Color.FromArgb(100, 100, 100);
            createRestorePoint.RippleOpacity = 0.3F;
            createRestorePoint.RippleRadiusMultiplier = 0.6F;
            createRestorePoint.ShadowBlur = 5;
            createRestorePoint.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            createRestorePoint.ShadowOffset = new Point(2, 2);
            createRestorePoint.ShakeDuration = 500;
            createRestorePoint.ShakeIntensity = 5;
            createRestorePoint.Size = new Size(216, 35);
            createRestorePoint.TabIndex = 43;
            createRestorePoint.Text = "Create Restore Point";
            createRestorePoint.TextAlign = ContentAlignment.MiddleCenter;
            createRestorePoint.TextColor = Color.White;
            createRestorePoint.TooltipText = null;
            createRestorePoint.UseAdvancedRendering = true;
            createRestorePoint.UseParticles = false;
            createRestorePoint.Click += createRestorePoint_Click;
            createRestorePoint.MouseClick += apply;
            createRestorePoint.MouseEnter += hover;
            // 
            // progressBarRestore
            // 
            progressBarRestore.Location = new Point(645, 306);
            progressBarRestore.Name = "progressBarRestore";
            progressBarRestore.Size = new Size(291, 23);
            progressBarRestore.TabIndex = 45;
            progressBarRestore.Visible = false;
            // 
            // lblRestoreStatus
            // 
            lblRestoreStatus.AutoSize = true;
            lblRestoreStatus.Font = new Font("Microsoft YaHei UI", 9F, FontStyle.Bold, GraphicsUnit.Point, 0);
            lblRestoreStatus.ForeColor = Color.White;
            lblRestoreStatus.Location = new Point(645, 332);
            lblRestoreStatus.Name = "lblRestoreStatus";
            lblRestoreStatus.Size = new Size(108, 17);
            lblRestoreStatus.TabIndex = 46;
            lblRestoreStatus.Text = "lblRestoreStatus";
            lblRestoreStatus.Visible = false;
            // 
            // siticoneButton1
            // 
            siticoneButton1.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard";
            siticoneButton1.AccessibleName = "X";
            siticoneButton1.AutoSizeBasedOnText = false;
            siticoneButton1.BackColor = Color.Transparent;
            siticoneButton1.BadgeBackColor = Color.Black;
            siticoneButton1.BadgeFont = new Font("Segoe UI", 8F, FontStyle.Bold);
            siticoneButton1.BadgeValue = 0;
            siticoneButton1.BadgeValueForeColor = Color.White;
            siticoneButton1.BorderColor = Color.Red;
            siticoneButton1.BorderWidth = 2;
            siticoneButton1.ButtonBackColor = Color.Black;
            siticoneButton1.ButtonImage = null;
            siticoneButton1.ButtonTextLeftPadding = 0;
            siticoneButton1.CanBeep = true;
            siticoneButton1.CanGlow = false;
            siticoneButton1.CanShake = true;
            siticoneButton1.ContextMenuStripEx = null;
            siticoneButton1.CornerRadiusBottomLeft = 5;
            siticoneButton1.CornerRadiusBottomRight = 5;
            siticoneButton1.CornerRadiusTopLeft = 5;
            siticoneButton1.CornerRadiusTopRight = 5;
            siticoneButton1.CustomCursor = Cursors.Default;
            siticoneButton1.DisabledTextColor = Color.FromArgb(150, 150, 150);
            siticoneButton1.EnableLongPress = false;
            siticoneButton1.EnablePressAnimation = true;
            siticoneButton1.EnableRippleEffect = false;
            siticoneButton1.EnableShadow = false;
            siticoneButton1.EnableTextWrapping = false;
            siticoneButton1.Font = new Font("Segoe UI Semibold", 10.2F);
            siticoneButton1.GlowColor = Color.FromArgb(100, 255, 255, 255);
            siticoneButton1.GlowIntensity = 100;
            siticoneButton1.GlowRadius = 20F;
            siticoneButton1.GradientBackground = false;
            siticoneButton1.GradientColor = Color.FromArgb(0, 227, 64);
            siticoneButton1.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            siticoneButton1.HintText = null;
            siticoneButton1.HoverBackColor = Color.FromArgb(0, 192, 0);
            siticoneButton1.HoverFontStyle = FontStyle.Regular;
            siticoneButton1.HoverTextColor = Color.Black;
            siticoneButton1.HoverTransitionDuration = 250;
            siticoneButton1.ImageAlign = ContentAlignment.MiddleLeft;
            siticoneButton1.ImagePadding = 5;
            siticoneButton1.ImageSize = new Size(16, 16);
            siticoneButton1.IsRadial = false;
            siticoneButton1.IsReadOnly = false;
            siticoneButton1.IsToggleButton = false;
            siticoneButton1.IsToggled = false;
            siticoneButton1.Location = new Point(958, 152);
            siticoneButton1.LongPressDurationMS = 1000;
            siticoneButton1.Name = "siticoneButton1";
            siticoneButton1.NormalFontStyle = FontStyle.Regular;
            siticoneButton1.ParticleColor = Color.FromArgb(200, 200, 200);
            siticoneButton1.ParticleCount = 15;
            siticoneButton1.PressAnimationScale = 0.97F;
            siticoneButton1.PressedBackColor = Color.FromArgb(0, 227, 64);
            siticoneButton1.PressedFontStyle = FontStyle.Regular;
            siticoneButton1.PressTransitionDuration = 150;
            siticoneButton1.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            siticoneButton1.RippleColor = Color.FromArgb(255, 255, 255);
            siticoneButton1.RippleOpacity = 0.3F;
            siticoneButton1.RippleRadiusMultiplier = 0.6F;
            siticoneButton1.ShadowBlur = 5;
            siticoneButton1.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            siticoneButton1.ShadowOffset = new Point(2, 2);
            siticoneButton1.ShakeDuration = 500;
            siticoneButton1.ShakeIntensity = 5;
            siticoneButton1.Size = new Size(23, 16);
            siticoneButton1.TabIndex = 47;
            siticoneButton1.Text = "X";
            siticoneButton1.TextAlign = ContentAlignment.MiddleCenter;
            siticoneButton1.TextColor = Color.White;
            siticoneButton1.TooltipText = null;
            siticoneButton1.UseAdvancedRendering = true;
            siticoneButton1.UseParticles = false;
            siticoneButton1.Click += siticoneButton1_Click;
            siticoneButton1.MouseClick += apply;
            siticoneButton1.MouseEnter += hover;
            siticoneButton1.MouseLeave += hover;
            // 
            // OtherTweaks
            // 
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.FromArgb(15, 15, 15);
            ClientSize = new Size(993, 694);
            Controls.Add(siticoneButton1);
            Controls.Add(lblRestoreStatus);
            Controls.Add(progressBarRestore);
            Controls.Add(createRestorePoint);
            Controls.Add(warrning);
            Controls.Add(back);
            Controls.Add(msiUtlity);
            Controls.Add(menuKillTime);
            Controls.Add(cleanTempFiles);
            Controls.Add(cpuTweaks);
            Controls.Add(i2);
            Controls.Add(i);
            Controls.Add(debloatStartup);
            Controls.Add(rebloat_Windows);
            Controls.Add(debloatWindows);
            Controls.Add(windowsGeneralSettings);
            Controls.Add(windowsPowerPlan);
            Controls.Add(windowsIOTweaks);
            Controls.Add(disableWinTelemetry);
            Controls.Add(label4);
            Controls.Add(label1);
            Controls.Add(panel1);
            Controls.Add(label2);
            FormBorderStyle = FormBorderStyle.None;
            Icon = (Icon)resources.GetObject("$this.Icon");
            Name = "OtherTweaks";
            Text = "Other Tweaks";
            Load += OtherTweaks_Load;
            panel1.ResumeLayout(false);
            panel1.PerformLayout();
            ResumeLayout(false);
            PerformLayout();
        }

        #endregion
        private Button blockWindowsUpdates;
        private Button generalWindowsSettings;
        private Button rebloatWindows;
        private Button debloatStartupApplications;
        private Panel panel1;
        private SiticoneNetCoreUI.SiticoneButton minimizeButton;
        private SiticoneNetCoreUI.SiticoneButton closeButton;
        private Label label3;
        private Label label4;
        private Label label1;
        private Label label2;
        private SiticoneNetCoreUI.SiticoneButton disableWinTelemetry;
        private SiticoneNetCoreUI.SiticoneButton windowsIOTweaks;
        private SiticoneNetCoreUI.SiticoneButton windowsPowerPlan;
        private SiticoneNetCoreUI.SiticoneButton windowsGeneralSettings;
        private SiticoneNetCoreUI.SiticoneButton debloatWindows;
        private SiticoneNetCoreUI.SiticoneButton rebloat_Windows;
        private SiticoneNetCoreUI.SiticoneButton debloatStartup;
        private SiticoneNetCoreUI.SiticoneButton i;
        private SiticoneNetCoreUI.SiticoneButton i2;
        private SiticoneNetCoreUI.SiticoneButton cpuTweaks;
        private SiticoneNetCoreUI.SiticoneButton cleanTempFiles;
        private SiticoneNetCoreUI.SiticoneButton menuKillTime;
        private SiticoneNetCoreUI.SiticoneButton msiUtlity;
        private SiticoneNetCoreUI.SiticoneButton back;
        private Label warrning;
        private SiticoneNetCoreUI.SiticoneButton createRestorePoint;
        private ProgressBar progressBarRestore;
        private Label lblRestoreStatus;
        private SiticoneNetCoreUI.SiticoneButton siticoneButton1;
    }
}